import { matchFromDictionary } from "./matcher-utils";
import type { MatchResult, ParsedNote } from "./types";

const DOMAIN_PHRASES: Record<string, string[]> = {
  math: [
    "math",
    "mathematics",
    "arithmetic",
    "number sense",
    "place value",
    "addition",
    "subtraction",
    "multiplication",
    "division",
    "fractions",
    "decimals",
    "percent",
    "percentage",
    "ratio",
    "proportion",
    "equations",
    "algebra",
    "geometry",
    "graphing",
    "coordinate plane",
    "ordered pairs",
    "slope",
    "integers",
    "positive and negative",
    "order of operations",
    "pemdas",
    "gemdas",
    "word problem",
    "word problems",
    "problem solving",
    "estimation",
    "rounding",
    "regrouping",
    "borrowing",
    "carrying",
    "factors",
    "multiples",
    "prime numbers",
    "exponents",
    "square roots",
    "area",
    "perimeter",
    "volume",
    "measurement",
    "data and graphing",
    "bar graph",
    "line plot",
    "probability",
    "statistics",
    "counting",
    "skip counting",
    "arrays",
    "number line",
    "ten frame",
    "base ten blocks",
    "manipulatives",
    "mental math",
    "fact fluency",
    "math facts",
    "timed test",
    "calculator",
    "show your work",
    "math workshop",
    "math centers",
    "iready math",
    "khan academy math",
  ],
  reading: [
    "reading",
    "literacy",
    "phonics",
    "phonemic awareness",
    "decode",
    "decoding",
    "encoding",
    "fluency",
    "oral reading",
    "read aloud",
    "comprehension",
    "reading comprehension",
    "main idea",
    "text evidence",
    "cite the text",
    "supporting details",
    "inference",
    "inferencing",
    "predict",
    "prediction",
    "summarize",
    "retell",
    "author's purpose",
    "compare and contrast",
    "sequence of events",
    "story elements",
    "character",
    "setting",
    "plot",
    "theme",
    "vocabulary",
    "context clues",
    "root word",
    "prefix",
    "suffix",
    "syllables",
    "blends",
    "digraph",
    "cvc words",
    "sight words",
    "high frequency words",
    "guided reading",
    "small group reading",
    "independent reading",
    "close reading",
    "annotating",
    "running record",
    "reading level",
    "lexile",
    "chapter book",
    "nonfiction",
    "fiction",
    "informational text",
    "words per minute",
    "wpm",
    "iready reading",
    "reading intervention",
    "reading specialist",
    "ela",
    "english language arts",
  ],
  writing: [
    "writing",
    "written response",
    "sentence",
    "complete sentence",
    "run on sentence",
    "sentence fragment",
    "paragraph",
    "multi paragraph",
    "essay",
    "narrative writing",
    "opinion writing",
    "informative writing",
    "expository",
    "persuasive writing",
    "grammar",
    "conventions",
    "punctuation",
    "capitalization",
    "spelling",
    "handwriting",
    "claim",
    "thesis",
    "hook",
    "introduction",
    "body paragraph",
    "conclusion",
    "transition words",
    "topic sentence",
    "supporting detail",
    "revise",
    "revision",
    "edit",
    "editing",
    "draft",
    "drafting",
    "prewrite",
    "graphic organizer",
    "outline",
    "peer review",
    "publishing",
    "rubric",
    "six traits",
    "ideas and content",
    "word choice",
    "sentence variety",
    "voice",
    "dialogue",
    "quotation marks",
    "cite sources",
    "research paper",
    "quick write",
    "journal",
    "writing workshop",
    "writing centers",
  ],
  behavior_social_emotional: [
    "behavior",
    "behaviour",
    "social emotional",
    "sel",
    "self regulation",
    "self-regulation",
    "dysregulated",
    "regulated",
    "meltdown",
    "escalated",
    "de-escalated",
    "calm down",
    "cool down",
    "coping skills",
    "coping strategy",
    "emotional",
    "emotions",
    "feelings",
    "frustrated",
    "anxious",
    "worried",
    "upset",
    "angry",
    "sad",
    "crying",
    "tears",
    "yelling",
    "shouting",
    "aggressive",
    "aggression",
    "hitting",
    "pushing",
    "peer conflict",
    "peer",
    "conflict",
    "arguing",
    "friendship",
    "social skills",
    "cooperation",
    "teamwork",
    "disrespect",
    "defiant",
    "noncompliance",
    "refusal",
    "shutdown",
    "shut down",
    "withdrawn",
    "isolating",
    "off task",
    "disruptive",
    "redirection",
    "restorative",
    "apology",
    "empathy",
    "bullying",
    "teased",
    "excluded",
    "zones of regulation",
    "check in",
    "sensory break",
    "overstimulated",
    "trigger",
    "hallway behavior",
    "lunchroom",
    "transition behavior",
    "following expectations",
    "classroom expectations",
    "behavior plan",
    "behavior contract",
    "point sheet",
  ],
  executive_functioning: [
    "executive functioning",
    "executive function",
    "executive skills",
    "attention",
    "sustained attention",
    "focus",
    "stay on task",
    "task initiation",
    "getting started",
    "work initiation",
    "organization",
    "organize materials",
    "organize binder",
    "planner",
    "agenda",
    "homework tracking",
    "directions",
    "follow directions",
    "multi step directions",
    "multi-step directions",
    "materials",
    "forgot materials",
    "lost assignment",
    "missing work",
    "incomplete work",
    "time management",
    "pacing",
    "procrastination",
    "working memory",
    "planning",
    "prioritize",
    "checklist",
    "goal setting",
    "self monitoring",
    "flexible thinking",
    "shift tasks",
    "transition between tasks",
    "impulse control",
    "impulsive",
    "blurting",
    "wait your turn",
    "binder check",
    "locker",
    "backpack",
    "forgot",
    "routine",
    "study skills",
    "metacognition",
  ],
  communication: [
    "parent",
    "parents",
    "guardian",
    "family",
    "caregiver",
    "email",
    "emailed",
    "email sent",
    "called",
    "phone call",
    "voicemail",
    "texted",
    "text home",
    "message home",
    "contacted home",
    "reached out",
    "spoke with",
    "talked to parent",
    "parent contact",
    "meeting",
    "conference",
    "parent teacher conference",
    "iep meeting",
    "504 meeting",
    "team meeting",
    "communication log",
    "note home",
    "send home",
    "signed planner",
    "progress report",
    "report card",
    "attendance call",
    "absent call",
    "translator",
    "interpreter",
    "responded",
    "reply",
    "follow up call",
    "follow-up email",
  ],
};

export function matchDomain(parsed: ParsedNote): MatchResult {
  return matchFromDictionary(parsed, DOMAIN_PHRASES);
}
